# Generated by Django 5.0.2 on 2024-02-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personrole',
            table='content.person_film_work',
        ),
    ]
